version: 1
disable_existing_loggers: false
formatters:
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: >-
      {{"timestamp": {asctime}{msecs:03.0f},
      "level": {levelno},
      "levelname": "{levelname}",
      "status": "{status_code}",
      "addr": "{client_addr}",
      "requestLine": "{request_line}",
      "authClientId": "{client_id}",
      "authUserId": "{user_id}"}}
    datefmt: '%s'
    style: '{'
    use_colors: false
  default:
    (): app._logging.NewlineRemovingFormatter
    fmt: >-
      {{"timestamp": {asctime}{msecs:03.0f},
      "level": {levelno},
      "levelname": "{levelname}",
      "msg": "{message}",
      "lineno": {lineno},
      "pathname": "{pathname}",
      "funcName": "{funcName}",
      "exception": "{exception}"}}
    datefmt: '%s'
    style: '{'
    use_colors: false
handlers:
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
loggers:
  uvicorn.access:
    handlers:
      - access
    level: INFO
    propagate: false
  uvicorn.error:
    handlers:
      - default
    level: INFO
    propagate: false
