branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - package.json
          from: ^\s*"version":\s*"\d+\.\d+.\d+",\s*$
          to: '  "version": "${nextRelease.version}",'
          results:
            - file: package.json
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - "@semantic-release/git"
    - assets:
        - package.json
        - CHANGELOG.md
